version: '3.8'

services:
    backend:
        image: geoapp
        build: .
        ports:
            - 8000:80
        volumes:
            - ./:/app
        env_file:
            - ./.env.example
        depends_on:
            - mongo

    mongo:
        image: mongo
        container_name: mongodb
        volumes:
            - ./data/db:/data/db
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
          ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        ports:
            - 8081:8081
        depends_on:
            - mongo